### ISSUE TITLE
something

### ISSUE THREAD

**Issue by ssrlive** [ssrlive/proxypool#17]
hi

**Comment by ssrlive** [comment]
source.yaml
```yaml
# 模糊抓取订阅链接webfuzzsub抓取（clash,config,json,txt,sub后缀文件）等
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
- type: webfuzzsub
  options:
    url: http://luo.openwert.icu/
- type: webfuzzsub
  options: 
    url: https://sub.id9.cc/sub?target=clash&url=http%3A%2F%2F121.4.209.91%3A8888%2Fdown%2FAnZWZKDstzLJ&insert=false

- type: webfuzzsub
  options: 
    url: https://api.suda.cat/sub?target=clash&url=http%3A%2F%2F121.4.209.91%3A8888%2Fdown%2FAnZWZKDstzLJ&insert=false
- type: webfuzzsub
  options: 
    url: https://api.sublink.dev/sub?target=clash&url=http%3A%2F%2F121.4.209.91%3A8888%2Fdown%2FAnZWZKDstzLJ&insert=false
- type: webfuzzsub
  options: 
    url: https://v2b.xiaoqikeji.tk/api/v1/client/subscribe?token=bf13f4b95f2f147bb346648dd20aba03
# 订阅链接-订阅地址Base64编码
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity
- type: subscribe
  options:
    url: 
# 网页模糊抓取-抓取网站所有的订阅地址
- type: webfuzz
  options:
    url: https://itlao5.com/wp/7034.html
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/123/
- type: webfuzz
  options:
    url: https://t.me/s/SSRlist?before=1378
- type: webfuzz
  options:
    url: https://github.com/zmike1993/hello-world/wiki/SSR%E5%85%8D%E8%B4%B9%E8%8A%82%E7%82%B9%EF%BC%88%E5%AE%9E%E6%97%B6%E6%9B%B4%E6%96%B0%EF%BC%89
- type: webfuzz
  options:
    url: https://github-wiki-see.page/m/zmike1993/hello-world/wiki/SSR%E5%85%8D%E8%B4%B9%E8%8A%82%E7%82%B9%EF%BC%88%E5%AE%9E%E6%97%B6%E6%9B%B4%E6%96%B0%EF%BC%89
- type: webfuzz
  options:
    url: https://docs.google.com/document/d/1x3b07u_AjVq137WIaiJDN_TbXP48NCSb9UQE8Ag1vVA/edit
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html
- type: webfuzz
  options:
    url: https://www.butnono.com/latest-2020-freevpn-v2ray-ss-ssr-address.html
- type: webfuzz
  options:
    url: https://ednovas.design/?ylrandomToken=4017&
- type: webfuzz
  options:
    url: https://sspool.nl/
- type: webfuzz
  options:
    url: https://proxy.yugogo.xyz/
- type: webfuzz
  options:
    url: https://freefq.com/free-ss/
- type: webfuzz
  options:
    url: https://lncn.org/
- type: webfuzz
  options:
    url: https://github.com/UmeLabs/node.umelabs.dev
- type: webfuzz
  options:
    url: https://github.com/colatiger/v2ray-nodes
- type: webfuzz
  options:
    url: https://freefq.com/v2ray/
- type: webfuzz
  options:
    url: https://freefq.com/free-ssr/
- type: webfuzz
  options:
    url: https://freefq.com/free-xray/
- type: webfuzz
  options:
    url: https://freefq.com/free-trojan/
- type: webfuzz
  options:
    url: 
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html
# clash格式订阅链接2
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
- type: clash
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
- type: clash
  options:
    url: https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/update/provider/config.yml
- type: clash
  options:
    url: https://github.com/learnhard-cn/free_proxy_ss/blob/main/clash/clash.provider.yamlhttps://cdn.jsdelivr.net/gh/alanbobs999/TopFreeProxies@master/update/provider/config-fastgit.yml
- type: clash
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
- type: clash
  options:
    url: 
# 某个网站抓取
- type: web-freessrxyz
  options:

```

**Comment by ssrlive** [comment]
```
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

- type: subscribe
  options:
    url: https://www.992266.xyz/api/v1/client/subscribe?token=ab825616355b0973e4cdfb659665965f

- type: subscribe
  options:
    url: https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg

- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

- type: clash
  options:
    url: http://49.233.28.108:1314/clash/proxies

    - type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

    - type: webfuzz
  options:
    url: https://doc.openit.ml/guide/

    - type: tgchannel
  options:
    channel: heinuhome
    num: 200
```
